### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by jaxmann** [jaxmann/pmr-server#16]
- added spaces in front of and after player names so "Can" isnt picked up inside Lezcano for instance (i check if " Can " is in the highlight string, instead of "Can"
- added tons of synonyms for every player - checked if player last name was unique, and if so, added first initial dot last name, first initial last name, and last name to list of player's own synonyms (and checked to make sure this didn't change the size of the player list - it's now called output.csv within server)

TODOS: 
- handle exceptions better - just run the program for a while and make sure exceptions dont crash the program (i.e. add try/catch blocks whever errors are raised)
- dont send multiple emails of the same highlight to the same user (idea: create a 2-minute-long buffer separate from the logs that just saves something like "email sent to x with player y" that only lasts for 2 minutes (could also be something like a queue, as long it can clear its data periodically)
- print lines that are intended to be used as log data should be output in a custom way (Log.print or something) and output to a file for every day (hour?) of logging - the folder should be on the gitignore. also add more logging data that is more helpful than currently for finding out exactly what the server is doing. also - add a timestamp for every log entry

@kevinchesser

**Comment by kevinchesser** [comment]
Timequeue is a good idea. Only per player though. The user should be able to get two emails if they had to do with a different play. I am pretty sure you were saying that too but I just wanted to be sure.

Logging is a bueno idea. We can still put them on stdout if you want but if we actually had users it would be impossible to look through.

**Comment by kevinchesser** [comment]
stdout is still find for our basic testing though

**Comment by kevinchesser** [comment]
slf4j set up by ya boy @jaxmann 
First and second point of todo still todo
