### ISSUE TITLE
chill out during non-peak hours and decrease refresh rate

### ISSUE THREAD

**Issue by jaxmann** [jaxmann/pmr-server#17]
default to 60 secs - could be more or less depending on time of day (and if weekend etc)

**Comment by jaxmann** [comment]
not worth optimizing days of the week because of world cup/champions league/premier league etc all have different schedules for weekdays depending on years and time of the year and whatnot, but we could say chill out at night and only check once per 10 mins and do once per 60 seconds otherwise?

**Comment by kevinchesser** [comment]
What times ranges are we defining as peak and off-peak?

**Comment by kevinchesser** [comment]
Peak: 7am to 7pm EST
Off-Peak: 7pm to 7am EST

**Comment by kevinchesser** [comment]
Completed
