### ISSUE TITLE
create timequeue

### ISSUE THREAD

**Issue by jaxmann** [jaxmann/pmr-server#19]
@kevinchesser here's how i'll do it:

 - write record to row to SQLite containing email, player, and timestamp every time an email is sent (I thought about making an object and writing it into Mongo or something but i don't think it's necessary)
 - create a job that runs every 1(?) minute that deletes records older than 2 minutes from the table - would run at the same time as the crawlerthread so the only issue is the fact that writing to db is slower than in-memory
 - right before an email is sent, execute a SQL query to see if "select email where player = player and timestamp is between now and 2 mins ago" returns anything. if so, don't send the email. (no need to overwrite the time to 2 mins again I think)

**Comment by kevinchesser** [comment]
Yeah I think that could work. I guess if there were actually a significant amount of users you'd want in-memory but SQLite should suffice for our needs.

**Comment by jaxmann** [comment]
need to add a cronjob and also test if this actually works... but other than that it's theoretically done

**Comment by jaxmann** [comment]
https://askubuntu.com/questions/2368/how-do-i-set-up-a-cron-job
